// Automated translation and localization helper for Thanaweya Biology content

const TERM_MAP: Record<string, string> = {
  // Key Biology Units & Chapters
  "الدعامة والحركة": "Support & Movement",
  "التنسيق الهرموني": "Hormonal Coordination",
  "التكاثر وتعاقب الأجيال": "Reproduction & Alternation of Generations",
  "التكاثر في الإنسان": "Human Reproduction",
  "المناعة في الكائنات الحية": "Immunity in Living Organisms",
  "البيولوجيا الجزيئية": "Molecular Biology",

  // Support & Movement (الدعامة والحركة)
  "الدعامة الفسيولوجية": "Physiological Support (Turgidity)",
  "الدعامة التركيبية": "Structural Support",
  "ضغط الامتلاء": "Turgor Pressure",
  "الخاصية الأسموزية": "Osmosis / Osmotic Property",
  "النسيج الكولنشيمي": "Collenchyma Tissue",
  "النسيج الاسكلرنشيمي": "Sclerenchyma Tissue",
  "النسيج البرنشيمي": "Parenchyma Tissue",
  "السليلوز": "Cellulose",
  "اللجنين": "Lignin",
  "الكيوتين": "Cutin",
  "السيبرين": "Suberin",
  "العمود الفقري": "Vertebral Column (33 Vertebrae / 26 Bones)",
  "الفقرات العنقودية": "Cervical Vertebrae (7)",
  "الفقرات الظهرية": "Thoracic Vertebrae (12)",
  "الفقرات القطنية": "Lumbar Vertebrae (5)",
  "الفقرات العجزية": "Sacral Vertebrae (5 fused / 1 bone)",
  "الفقرات العصعصية": "Coccygeal Vertebrae (4 fused / 1 bone)",
  "الجمجمة": "Skull (Cranium & Facial Bones)",
  "القفص الصدري": "Rib Cage (Thoracic Cage)",
  "الحزام الصدري": "Pectoral Girdle (Clavicle & Scapula)",
  "الحزام الحوضي": "Pelvic Girdle (Ilium, Ischium, Pubis)",
  "الأربطة": "Ligaments (Connect bone to bone)",
  "الأوتار": "Tendons (Connect muscle to bone)",
  "وتر أخيل": "Achilles Tendon",
  "المفاصل الزلالية": "Synovial Joints",
  "المفاصل الغضروفية": "Cartilaginous Joints",
  "المفاصل الليفية": "Fibrous Joints",
  "السائل الزلالي": "Synovial Fluid",

  // Muscular System & Contraction (الجهاز العضلي والانقباض)
  "القطعة العضلية": "Sarcomere",
  "الروابط المستعرضة": "Cross-Bridges (Myosin Heads)",
  "خيوط الأكتين": "Actin Filaments (Thin)",
  "خيوط الميوسين": "Myosin Filaments (Thick)",
  "أيونات الكالسيوم": "Calcium Ions (Ca2+)",
  "الوصلة العصبية العضلية": "Neuromuscular Junction (NMJ / Motor End Plate)",
  "إجهاد العضلة": "Muscle Fatigue (Lactic Acid Accumulation)",
  "الشد العضلي": "Muscle Cramp / Spasm (ATP Depletion)",
  "نظرية الخيوط المنزلقة": "Sliding Filament Theory (Huxley)",
  "المنطقة المضيئة (I)": "Isotropic Zone (I-band)",
  "المنطقة الداكنة (A)": "Anisotropic Zone (A-band)",
  "المنطقة شبه المضيئة (H)": "Semi-clear Zone (H-zone)",
  "خط Z": "Z-line",
  "الوحدة الحركية": "Motor Unit",
  "استيل كولين": "Acetylcholine (ACh)",
  "كولين إستريز": "Cholinesterase Enzyme",
  "حمض اللاكتيك": "Lactic Acid",
  "غشاء الليفة العضلية": "Sarcolemma",
  "سيتوبلازم العضلة": "Sarcoplasm",

  // Hormonal Coordination (التنسيق الهرموني)
  "غدة": "Gland",
  "غدة صماء": "Endocrine Gland (Ductless)",
  "غدة قنوية": "Exocrine Gland (Duct)",
  "غدة مشتركة": "Mixed/Heterocrine Gland (Pancreas & Gonads)",
  "الغدة النخامية": "Pituitary Gland (Master Gland)",
  "الغدة الدرقية": "Thyroid Gland",
  "الغدة الجاردرقية": "Parathyroid Gland",
  "الغدة الكظرية": "Adrenal Gland (Cortex & Medulla)",
  "البنكرياس": "Pancreas (Islets of Langerhans)",
  "هرمون النمو": "Growth Hormone (GH)",
  "هرمون الثيروكسين": "Thyroxin Hormone",
  "هرمون الكالسيتونين": "Calcitonin (Lowers blood calcium)",
  "هرمون الباراثورمون": "Parathormone / PTH (Raises blood calcium)",
  "الأنسولين": "Insulin (Decreases blood glucose)",
  "الجلوكاجون": "Glucagon (Increases blood glucose)",
  "الأدرينالين": "Adrenaline / Epinephrine (Emergency hormone)",
  "النورأدرينالين": "Noradrenaline / Norepinephrine",
  "الكورتيزون": "Cortisone",
  "الألدوستيرون": "Aldosterone (Reabsorbs Na+, secretes K+)",
  "هرمون ADH": "ADH / Vasopressin (Anti-Diuretic Hormone)",
  "هرمون الأوكسيتوسين": "Oxytocin (Uterine contraction & Milk ejection)",
  "هرمون ACTH": "ACTH Hormone",
  "هرمون TSH": "TSH Hormone",
  "الأوكسينات": "Auxins (Plant Hormones - IAA)",
  "التغذية الراجعة السلبية": "Negative Feedback Mechanism",
  "التغذية الراجعة الإيجابية": "Positive Feedback Mechanism",

  // Reproduction & Life Cycles (التكاثر وتعاقب الأجيال)
  "الانقسام الميوزي": "Meiosis (Reduction Division)",
  "الانقسام الميتوزي": "Mitosis (Equational Division)",
  "التكاثر اللاجنسي": "Asexual Reproduction",
  "التكاثر الجنسي": "Sexual Reproduction",
  "التجدد": "Regeneration (Planaria, Hydra, Starfish)",
  "التبرعم": "Budding (Yeast, Hydra)",
  "التجرثم": "Sporogony / Sporulation (Bread Mold, Ferns)",
  "التوالد البكري": "Parthenogenesis (Honeybees & Aphids)",
  "زراعة الأنسجة": "Tissue Culture (Carrots & Tobacco)",
  "تعاقب الأجيال": "Alternation of Generations",
  "بلازموديوم الملاريا": "Plasmodium Malariae",
  "نبات الفوجير": "Polypodium (Fern)",
  "الطور الممشجي": "Gametophyte (Haploid 1n)",
  "الطور الجرثومي": "Sporophyte (Diploid 2n)",
  "الميروزويتات": "Merozoites (Asexual inside RBCs & Liver)",
  "السبوروزويتات": "Sporozoites (Infective stage in saliva)",
  "الزيجوت": "Zygote (2n)",
  "أوكينيت": "Ookinete (Motile Zygote 2n)",
  "كيس البيض": "Oocyst (1n inside Mosquito stomach wall)",
  "الأنتيريديا": "Antheridia (Male Gametangia)",
  "الأرشيجونيا": "Archegonia (Female Gametangia)",
  "دورة الطمث": "Menstrual Cycle",
  "هرمون FSH": "FSH (Follicle Stimulating Hormone)",
  "هرمون LH": "LH (Luteinizing Hormone)",
  "الاستروجين": "Estrogen (Estradiol)",
  "البروجسترون": "Progesterone",
  "الإخصاب خارج الرحم": "In Vitro Fertilization (IVF / Test-tube babies)",
  "طفل الأنابيب": "Test-tube Baby (IVF)",

  // Immunology (المناعة)
  "خط الدفاع الأول": "First Line of Defense (Skin, Mucus, Tears, HCl, Sweat)",
  "خط الدفاع الثاني": "Second Line of Defense (Inflammation, Interferons, NK)",
  "خط الدفاع الثالث": "Third Line of Defense (Specific Immunity: Humoral & Cell-Mediated)",
  "الاستجابة بالالتهاب": "Inflammatory Response (Histamine release)",
  "الهستامين": "Histamine (Vasodilator released by Mast cells & Basophils)",
  "الخلايا البائية": "B-Lymphocytes (B-Cells / Plasma B-Cells)",
  "الخلايا التائية": "T-Lymphocytes (T-Cells: Th, Tc, Ts)",
  "الخلايا التائية المساعدة": "Helper T-Cells (Th - CD4+)",
  "الخلايا التائية القاتلة": "Cytotoxic T-Cells (Tc - CD8+)",
  "الخلايا التائية الكابحة": "Suppressor/Regulatory T-Cells (Ts - CD8+)",
  "الخلايا البلعمية الكبيرة": "Macrophages (Fixed & Wandering)",
  "الخلايا القاتلة الطبيعية": "Natural Killer (NK) Cells",
  "الأجسام المضادة": "Antibodies (Immunoglobulins: IgG, IgM, IgA, IgD, IgE)",
  "المتممات": "Complement System (Lysis & Opsonization)",
  "الإنترفيلونات": "Interferons (Anti-viral proteins)",
  "بروتين التوافق النسيجي": "Major Histocompatibility Complex (MHC)",
  "الإنترلوكينات": "Interleukins (ILs - Communication between immune cells)",
  "السيتوكينات": "Cytokines (Attract & activate phagocytes/cells)",
  "البرفورين": "Perforin (Pore-forming Protein)",
  "السموم الليمفاوية": "Lymphotoxins (Activate apoptosis genes)",
  "المناعة الخلطية": "Humoral Immunity (Antibody-Mediated)",
  "المناعة الخلوية": "Cell-Mediated Immunity (T-Cell Mediated)",

  // Molecular Biology & DNA/RNA (البيولوجيا الجزيئية)
  "تحول بكتيري": "Bacterial Transformation (Griffith's Experiment)",
  "تجربة غريفيث": "Griffith's Transformation Experiment",
  "تجربة إيفري": "Avery's Experiment (DNA is the genetic material)",
  "تجربة هيرشي وتشيس": "Hershey-Chase Experiment (Radioactive P32 & S35)",
  "تضاعف DNA": "DNA Replication (Semi-conservative)",
  "إنزيم اللولب": "Helicase Enzyme (Unwinds double helix)",
  "إنزيم البلمرة": "DNA Polymerase (Synthesizes 5' to 3')",
  "إنزيم الربط": "DNA Ligase (Joins Okazaki fragments & repairs DNA)",
  "إنزيمات القصر": "Restriction Enzymes (Endonucleases)",
  "البلازميد": "Plasmid (Circular extra-chromosomal DNA)",
  "كودون البدء": "Start Codon (AUG - Codes for Methionine)",
  "كودون الوقف": "Stop Codon (UAA, UAG, UGA - No amino acid)",
  "الطفرات": "Mutations (Gene Mutations & Chromosomal Mutations)",
  "الهندسة الوراثية": "Genetic Engineering (Recombinant DNA Technology)",
  "الشفرة الوراثية": "Genetic Code (Triplets)",
  "tRNA": "Transfer RNA (tRNA - Transport amino acids)",
  "mRNA": "Messenger RNA (mRNA - Carries genetic code)",
  "rRNA": "Ribosomal RNA (rRNA - Forms Ribosomes)",
  "موقع الببتيديل": "Peptidyl Site (P site)",
  "موقع الأمينوأسيل": "Aminoacyl Site (A site)",
  "مضاد الكودون": "Anticodon",

  // Common Sentence Patterns & Question Stems
  "أي مما يلي": "Which of the following",
  "أي الكائنات التالية": "Which of the following organisms",
  "أي الهرمونات التالية": "Which of the following hormones",
  "أي الأنسجة التالية": "Which of the following tissues",
  "أي الخلايا التالية": "Which of the following cells",
  "أي الإنزيمات التالية": "Which of the following enzymes",
  "أي البدائل التالية": "Which of the following alternatives",
  "ما السبب في": "What is the cause of",
  "ما التغير الذي يحدث": "What change occurs",
  "ما النتيجة المترتبة على": "What is the result of",
  "ما أهمية": "What is the importance of",
  "ما وظيفه": "What is the function of",
  "النسبة بين": "The ratio between",
  "كم عدد": "How many",
  "عدد القطع العضلية": "Number of sarcomeres",
  "عدد مناطق H": "Number of H-zones",
  "عدد خطوط Z": "Number of Z-lines",
  "عند انقباض العضلة": "Upon muscle contraction",
  "عند انبساط العضلة": "Upon muscle relaxation",
  "في الشكل المقابل": "In the shown diagram",
  "في المنحنى البياني": "In the graph",
  "يمثل الشكل": "The figure represents",
  "يشير الحرف": "The letter indicates",
  "زيادة إفراز": "Increased secretion of",
  "نقص إفراز": "Decreased secretion of",
  "تثبيط": "Inhibition of",
  "تحفيز": "Stimulation of",
  "استجابة": "Response",
  "التفسير العلمي": "Scientific Explanation",
  "الإجابة النموذجية": "Model Answer",
  "التفسير الصحيح": "Correct Explanation",
  "الربط بين الفصول": "Cross-chapter Connection",
  "الفكرة المحورية": "Core Concept",
  "خطأ شائع": "Common Misconception",
  "تنبيه هام": "Important Alert",
  "مفاهيم أساسية": "Key Concepts",
  "تريكات الامتحانات": "Exam Tricks",

  // Exam Meta Tags
  "دور أول 2021": "1st Session 2021",
  "دور أول 2022": "1st Session 2022",
  "دور أول 2023": "1st Session 2023",
  "دور أول 2024": "1st Session 2024",
  "دور أول 2025": "1st Session 2025",
  "تجريبي 2024": "Experimental 2024",
  "تجريبي 2025": "Experimental 2025",
  "تجريبي 2026": "Experimental 2026",
  "رسمي": "Official Ministry Exam",
  "سهل": "Easy",
  "متوسط": "Medium",
  "متقدم": "High",
  "خبير": "Expert"
};

export function autoTranslateText(text: string | undefined): string {
  if (!text) return '';
  
  let translated = text;

  // Exact term matches
  if (TERM_MAP[text]) {
    return TERM_MAP[text];
  }

  // Replace phrases iteratively (longest phrases first to avoid partial replacements)
  const keysSorted = Object.keys(TERM_MAP).sort((a, b) => b.length - a.length);

  keysSorted.forEach(key => {
    if (translated.includes(key)) {
      translated = translated.replaceAll(key, TERM_MAP[key]);
    }
  });

  return translated;
}
